# version: "3.9"

services:

  db:
    image: mariadb:10.6
    container_name: kamailio-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kamailio
      MYSQL_USER: kamailio
      MYSQL_PASSWORD: kamailio
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  kamailio:
    build: ./Kamailio
    container_name: kamailio
    restart: always
    depends_on:
      - db
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
    volumes:
      - ./kamailio/kamailio.cfg:/etc/kamailio/kamailio.cfg
